
import { Instrument } from '../../types/calculations';

export const INSTRUMENT_PRESETS: Partial<Instrument>[] = [
  {
    symbol: 'XAUUSD',
    name: 'Gold vs US Dollar',
    category: 'precious-metals',
    subcategory: 'gold',
    broker: 'XM',
    isActive: true,
    calculationMode: 'direct_points_money',
    contractSize: 100,
    referenceLot: 0.01,
    referencePoints: 100,
    referenceMoneyValue: 1,
    pointSize: 0.01,
    quoteCurrency: 'USD',
    accountCurrency: 'USD',
    pricePrecision: 2,
    notes: '100 points with 0.01 lot = 1 USD (XM Standard)'
  },
  {
    symbol: 'XAGUSD',
    name: 'Silver vs US Dollar',
    category: 'precious-metals',
    subcategory: 'silver',
    broker: 'XM',
    isActive: true,
    calculationMode: 'direct_points_money',
    contractSize: 5000,
    referenceLot: 0.01,
    referencePoints: 100,
    referenceMoneyValue: 5,
    pointSize: 0.01,
    quoteCurrency: 'USD',
    accountCurrency: 'USD',
    pricePrecision: 3,
    notes: 'Silver has higher volatility and contract size than Gold'
  },
  {
    symbol: 'EURUSD',
    name: 'Euro vs US Dollar',
    category: 'forex',
    subcategory: 'major',
    broker: 'XM',
    isActive: true,
    calculationMode: 'direct_points_money',
    contractSize: 100000,
    referenceLot: 0.01,
    referencePoints: 100,
    referenceMoneyValue: 1,
    pointSize: 0.00001,
    pipSize: 0.0001,
    quoteCurrency: 'USD',
    accountCurrency: 'USD',
    pricePrecision: 5,
    notes: 'Standard Forex calculation'
  },
  {
    symbol: 'GBPUSD',
    name: 'Great Britain Pound vs US Dollar',
    category: 'forex',
    subcategory: 'major',
    broker: 'XM',
    isActive: true,
    calculationMode: 'direct_points_money',
    contractSize: 100000,
    referenceLot: 0.01,
    referencePoints: 100,
    referenceMoneyValue: 1,
    pointSize: 0.00001,
    pipSize: 0.0001,
    quoteCurrency: 'USD',
    accountCurrency: 'USD',
    pricePrecision: 5,
  },
  {
    symbol: 'BTCUSD',
    name: 'Bitcoin vs US Dollar',
    category: 'crypto',
    broker: 'XM',
    isActive: true,
    calculationMode: 'direct_points_money',
    contractSize: 1,
    referenceLot: 0.01,
    referencePoints: 1000,
    referenceMoneyValue: 10,
    pointSize: 0.01,
    quoteCurrency: 'USD',
    accountCurrency: 'USD',
    pricePrecision: 2,
  },
  {
    symbol: 'ETHUSD',
    name: 'Ethereum vs US Dollar',
    category: 'crypto',
    broker: 'XM',
    isActive: true,
    calculationMode: 'direct_points_money',
    contractSize: 10,
    referenceLot: 0.01,
    referencePoints: 100,
    referenceMoneyValue: 1,
    pointSize: 0.01,
    quoteCurrency: 'USD',
    accountCurrency: 'USD',
    pricePrecision: 2,
  },
  {
    symbol: 'BRENTCash',
    name: 'Brent Crude Oil Cash',
    category: 'energies',
    subcategory: 'oil',
    broker: 'XM',
    isActive: true,
    calculationMode: 'direct_points_money',
    contractSize: 100,
    referenceLot: 0.01,
    referencePoints: 100,
    referenceMoneyValue: 1,
    pointSize: 0.01,
    quoteCurrency: 'USD',
    accountCurrency: 'USD',
    pricePrecision: 2,
  },
  {
    symbol: 'OILCash',
    name: 'WTI Crude Oil Cash',
    category: 'energies',
    subcategory: 'oil',
    broker: 'XM',
    isActive: true,
    calculationMode: 'direct_points_money',
    contractSize: 100,
    referenceLot: 0.01,
    referencePoints: 100,
    referenceMoneyValue: 1,
    pointSize: 0.01,
    quoteCurrency: 'USD',
    accountCurrency: 'USD',
    pricePrecision: 2,
  }
];
